name: Context Workflow
on: push

jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Context
        run: echo '${{ toJson(github) }}'
      - name: Print ENV variables
        run: echo '${{ toJson(env) }}'
  runner:
    runs-on: ubuntu-latest
    steps:
    - name: Runner details
      run: echo '{{ toJso(runner) }}'
  
