name: github_context_properties
on: push
jobs:
  github_context_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: |
           echo "Job Container: ${{ job.container }}"
           echo "Job Container ID: ${{ job.container.id }}"
           echo "Job Container Network: ${{ job.container.network }}"
           echo "Job Services: ${{ job.services }}"
           echo "Job Status: ${{ job.status }}"
          
