name: github_context_properties
on: push
jobs:
  github_context_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
           echo "${{ RUNNER_CONTEXT }}"
          
