name: github_context_properties
on: push
jobs:
  github_context_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: |
          echo "Event type: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
